# -*- coding: utf-8 -*-
"""Data Cleaning & EDA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SRcSUDhfwRvZ5scpnsxnPG9uSnW8tXSK
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

print("\n Step 2: Loading the dataset")

df = pd.read_csv("/content/zomato.csv" , encoding='latin-1', engine='python', on_bad_lines='skip')
print(f"{df.shape}")
print(f"This means:{df.shape[0]} rows (restaurents) and {df.shape[1]} columns (features)")

df.head(10)

df.columns

df.tail(5)

for i, col in enumerate(df.columns, 1):
  print(f"{i:2}.{col}")

print(df.dtypes)

df.info()

print(df.describe())

print(df.isnull())

df.isnull().sum()

[r for r in df.columns if df[r].isnull().sum()>0]

sns.heatmap(df.isnull(),yticklabels=False,cbar=False,cmap='viridis')

mean_data = df['rate'].mean
print(mean_data)
replace = df['rate'].fillna(mean_data, inplace=True)
print(replace)

df.isnull().sum()

df['rate'] = df['rate'].astype(str)
print(df['rate'].dtype)

df['rate']=df['rate'].astype(str)

df['rate']=df['rate'].str.replace('/5','',regex=False).str.strip()

df['rate']=df['rate'].replace({'NEW':np.nan,'nan':np.nan,'-':np.nan})

df['rate']=pd.to_numeric(df['rate'],errors='coerce')

from pandas.core.arrays import numeric
df['rate'] = df['rate'].astype(float)
print(df['rate'].dtype)

print(df['phone'].isnull().sum())

df.dropna(subset=['phone'], inplace=True)

print(f"Number of null values in 'phone' column after dropping: {df['phone'].isnull().sum()}")

df['phone'] = df['phone'].astype(str)
print(df['phone'].dtype)

df['phone'] = df['phone'].astype(str)

df["phone1","phone2"]=df["phone"].str.split(r"\r\n", n=1 , expand=True)
display(df.head(2))
df['phone'].head(5)

df['location']
location_names=df.location.value_counts().index
print(location_names)

location_value=df.location.value_counts().values
print(location_value)

plt.pie(location_value, labels=location_names)
plt.show()

plt.pie(location_value[:10], labels=location_names[:10], autopct='%1.3f%%')
plt.show()

display(df.head(2))

df['votes'].describe()

votes_mean = df['votes'].mean()
votes_median = df['votes'].median()
votes_mode = df['votes'].mode()
print(f"Mean: {votes_mean}")
print(f"Median: {votes_median}")
print(f"Mode: {votes_mode}")

plt.figure(figsize=(8, 5))   # (x,y)
plt.hist(df['votes'], bins=30)

plt.xlabel('Votes')
plt.ylabel('Number of Restaurents')
plt.title('Distribution of Votes')
plt.show()

plt.figure(figsize=(8, 5))   # (x,y)
plt.hist(df['votes'], bins=10)

plt.xlabel('Votes')
plt.ylabel('Number of Restaurents')
plt.title('Distribution of Votes')
plt.show()

plt.figure(figsize=(8, 5))   # (x,y)
plt.hist(df['votes'], bins=20)

plt.xlabel('Votes')
plt.ylabel('Number of Restaurents')
plt.title('Distribution of Votes')
plt.show()

top_reataurants = df.nlargest(10, "votes")

plt.figure(figsize=(10, 5))
plt.bar(top_reataurants['name'], top_reataurants['votes'])

plt.xticks(rotation=45)
plt.xlabel('Restaurant Name')
plt.ylabel('Votes')
plt.title('Top 10 Restaurants by Votes')
plt.xticks(rotation=90)
plt.show()

"""## Analysis of Online Orders"""

# Count the occurrences of 'Yes' and 'No' in the 'online_order' column
online_order_counts = df['online_order'].value_counts()
display(online_order_counts)

# Create a bar graph
plt.figure(figsize=(7, 5))
sns.barplot(x=online_order_counts.index, y=online_order_counts.values, palette='viridis', hue=online_order_counts.index, legend=False)
plt.title('Distribution of Online Orders')
plt.xlabel('Online Order Available')
plt.ylabel('Number of Restaurants')
plt.show()